Vagrant.configure("2") do |config|
  # Для macOS на платформі ARM64 використовується Ubuntu 22.04 ARM64
  if Vagrant::Util::Platform.mac? && !Vagrant::Util::Platform.windows?
    config.vm.box = "ubuntu/22.04-arm64"

    # Використовуємо Parallels на macOS
    config.vm.provider "parallels" do |prl|
      prl.name = "Lab4App"
      prl.memory = 2048
      prl.cpus = 2
    end
  else
    # Для Windows використовуємо Ubuntu 22.04 x64
    config.vm.box = "ubuntu/22.04"

    # Використовуємо VirtualBox на Windows
    config.vm.provider "virtualbox" do |vb|
      vb.name = "Lab4App"
      vb.memory = 2048
      vb.cpus = 2
    end
  end

  # Перенаправлення портів
  config.vm.network "forwarded_port", guest: 5000, host: 4321

  # Провізія для Docker і BaGet
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install -y docker.io
    sudo docker run -d -p 5000:80 --name baget loicsharma/baget:latest
  SHELL
end
