Vagrant.configure("2") do |config|
  # Використовуємо Ubuntu 22.04 ARM
  config.vm.box = "ubuntu/22.04-arm64"

  # Використання провайдера Parallels
  config.vm.provider "parallels" do |prl|
    prl.name = "Lab4App"
    prl.memory = 2048
    prl.cpus = 2
  end

  # Перенаправлення портів
  config.vm.network "forwarded_port", guest: 5000, host: 4321

  # Провізія для Docker і BaGet
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install -y docker.io
    sudo docker run -d -p 5000:80 --name baget loicsharma/baget:latest
  SHELL
end
